publishDir = "docs/"
languageCode = "en-us"
baseurl = "https://jamesstrong.dev/"
title = "James Strong"
copyright = "Copyright (c) 2015, all rights reserved."
canonifyurls = true
paginate = 3
theme = "blackburn"

disqusShortname = "jamesstrong-dev"

[params]
  # Shown in the home page
  brand = "James Strong"
  googleAnalytics = "G-Y034J08BEQ"
  dateFormat = "Jan 2, 2006"

[indexes]
  tag = "tags"
  topic = "topics"

[taxonomies]
  tag = "tags"

[social]
  github = "strongjz"
  twitter = "strongjz"
  linkedin = "strongjames"
  email = "james.strong@linux.com"

  # SNS photo/video sharing
  slideshare = "jstrong09"

  reddit = "strongjz"
  hackernews = "strongbad"

  gitlab = "strongjz"
  bitbucket = "strongjz"
  stackoverflow = "1794802"
  serverfault = "162720"

  # Other
  keybase = "strongjz"

[author]
  name = "James Strong"


[[menu.main]]

  name = "Home"
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "About Me"
  identifier = "about"
  url = "/about/"

[[menu.main]]

  name = "Posts"
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "Resume"
  identifier = "resume"
  url = "/resume/"

[[menu.main]]
  name = "Keybase"
  identifier = "Keybase"
  url = "/keybase.txt"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."
