publishDir = "docs/"
languageCode = "en-us"
baseurl = "https://jamesstrong.dev/"
title = "James Strong"
copyright = "Copyright (c) 2017, all rights reserved."
canonifyurls = true
paginate = 3
theme = "blackburn"

 dateFormat = "02 Jan 2006"

[indexes]
  tag = "tags"
  topic = "topics"

[taxonomies]
  tag = "tags"

[params]
  github = "strongjz"
  twitter = "strongjz"
  linkedin = "strongjames"
  email = "strong.james.e@gmail.com"
  author = "James Strong"
  locale = "en-US"


[author]
  name = "James Strong"


[[menu.main]]

  name = "Home"
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "About Me"
  identifier = "about"
  url = "/about/"

[[menu.main]]

  name = "Posts"
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "Resume"
  identifier = "resume"
  url = "/resume/"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."
