publishDir = "docs/"
languageCode = "en-us"
baseurl = "https://jamesstrong.dev/"
title = "James Strong"
copyright = "Copyright (c) 2017, all rights reserved."
canonifyurls = true
paginate = 3
theme = "blackburn"

dateFormat = "02 Jan 2006"

[indexes]
  tag = "tags"
  topic = "topics"

[taxonomies]
  tag = "tags"

[social]
  github = "strongjz"
  twitter = "strongjz"
  linkedin = "strongjames"
  email = "strong.james.e@gmail.com"


  # SNS photo/video sharing
  slideshare = "jstrong09"

  reddit = "strongjz"
  hackernews = "strongbad"

  gitlab = "strongjz"
  bitbucket = "*"
  stackoverflow = "1794802"
  serverfault = "162720"

  # Other
  keybase = "strongjz"


[author]
  name = "James Strong"


[[menu.main]]

  name = "Home"
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "About Me"
  identifier = "about"
  url = "/about/"

[[menu.main]]

  name = "Posts"
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "Resume"
  identifier = "resume"
  url = "/resume/"

[[menu.main]]
  name = "Keybase"
  identifier = "Keybase"
  url = "/keybase.txt"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."
